sumologic:
  accessId: suROE7Xvsvzz5H
  accessKey: qquj3QULrJzMeNodYe0JhfVZ8Zed7amaeJVe1u8GIsASkcP5xmZrifs2feopO47Q
  clusterName: skc-cluster
  endpoint: https://long-api.sumologic.net/api/
  traces:
    enabled: false

fluentd:
  metrics:
    statefulset:
      replicaCount: 1
  logs:
    statefulset:
      replicaCount: 1
    autoscaling:
      enabled: false
